// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pkg/shortenerservice/shortenerservice.proto

package shortenerservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLShortenRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url string                 `protobuf:"bytes,1,opt,name=url,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *URLShortenRequest) Reset() {
	*x = URLShortenRequest{}
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenRequest) ProtoMessage() {}

func (x *URLShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLShortenRequest) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *URLShortenRequest) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

type URLShortenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url string
}

func (b0 URLShortenRequest_builder) Build() *URLShortenRequest {
	m0 := &URLShortenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = b.Url
	return m0
}

type URLShortenResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result string                 `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *URLShortenResponse) Reset() {
	*x = URLShortenResponse{}
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenResponse) ProtoMessage() {}

func (x *URLShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLShortenResponse) GetResult() string {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return ""
}

func (x *URLShortenResponse) SetResult(v string) {
	x.xxx_hidden_Result = v
}

type URLShortenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result string
}

func (b0 URLShortenResponse_builder) Build() *URLShortenResponse {
	m0 := &URLShortenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

type URLExpandRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandRequest) Reset() {
	*x = URLExpandRequest{}
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandRequest) ProtoMessage() {}

func (x *URLExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLExpandRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *URLExpandRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type URLExpandRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 URLExpandRequest_builder) Build() *URLExpandRequest {
	m0 := &URLExpandRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type URLExpandResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result string                 `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *URLExpandResponse) Reset() {
	*x = URLExpandResponse{}
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandResponse) ProtoMessage() {}

func (x *URLExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLExpandResponse) GetResult() string {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return ""
}

func (x *URLExpandResponse) SetResult(v string) {
	x.xxx_hidden_Result = v
}

type URLExpandResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result string
}

func (b0 URLExpandResponse_builder) Build() *URLExpandResponse {
	m0 := &URLExpandResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

type UserURLsResponse struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url *[]*URLData            `protobuf:"bytes,1,rep,name=url,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserURLsResponse) GetUrl() []*URLData {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
	}
	return nil
}

func (x *UserURLsResponse) SetUrl(v []*URLData) {
	x.xxx_hidden_Url = &v
}

type UserURLsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url []*URLData
}

func (b0 UserURLsResponse_builder) Build() *UserURLsResponse {
	m0 := &UserURLsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = &b.Url
	return m0
}

type URLData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ShortUrl    string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3"`
	xxx_hidden_OriginalUrl string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *URLData) Reset() {
	*x = URLData{}
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLData) GetShortUrl() string {
	if x != nil {
		return x.xxx_hidden_ShortUrl
	}
	return ""
}

func (x *URLData) GetOriginalUrl() string {
	if x != nil {
		return x.xxx_hidden_OriginalUrl
	}
	return ""
}

func (x *URLData) SetShortUrl(v string) {
	x.xxx_hidden_ShortUrl = v
}

func (x *URLData) SetOriginalUrl(v string) {
	x.xxx_hidden_OriginalUrl = v
}

type URLData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ShortUrl    string
	OriginalUrl string
}

func (b0 URLData_builder) Build() *URLData {
	m0 := &URLData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ShortUrl = b.ShortUrl
	x.xxx_hidden_OriginalUrl = b.OriginalUrl
	return m0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shortenerservice_shortenerservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Empty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Empty_builder) Build() *Empty {
	m0 := &Empty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_pkg_shortenerservice_shortenerservice_proto protoreflect.FileDescriptor

const file_pkg_shortenerservice_shortenerservice_proto_rawDesc = "" +
	"\n" +
	"+pkg/shortenerservice/shortenerservice.proto\x12\x10shortenerservice\"%\n" +
	"\x11URLShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x12URLShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\"\n" +
	"\x10URLExpandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11URLExpandResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"?\n" +
	"\x10UserURLsResponse\x12+\n" +
	"\x03url\x18\x01 \x03(\v2\x19.shortenerservice.URLDataR\x03url\"I\n" +
	"\aURLData\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"\a\n" +
	"\x05Empty2\x8e\x02\n" +
	"\x10ShortenerService\x12W\n" +
	"\n" +
	"ShortenURL\x12#.shortenerservice.URLShortenRequest\x1a$.shortenerservice.URLShortenResponse\x12T\n" +
	"\tExpandURL\x12\".shortenerservice.URLExpandRequest\x1a#.shortenerservice.URLExpandResponse\x12K\n" +
	"\fListUserURLs\x12\x17.shortenerservice.Empty\x1a\".shortenerservice.UserURLsResponseB9Z7github.com/konkovaanna23/shortener/pkg/shortenerserviceb\x06proto3"

var file_pkg_shortenerservice_shortenerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_shortenerservice_shortenerservice_proto_goTypes = []any{
	(*URLShortenRequest)(nil),  // 0: shortenerservice.URLShortenRequest
	(*URLShortenResponse)(nil), // 1: shortenerservice.URLShortenResponse
	(*URLExpandRequest)(nil),   // 2: shortenerservice.URLExpandRequest
	(*URLExpandResponse)(nil),  // 3: shortenerservice.URLExpandResponse
	(*UserURLsResponse)(nil),   // 4: shortenerservice.UserURLsResponse
	(*URLData)(nil),            // 5: shortenerservice.URLData
	(*Empty)(nil),              // 6: shortenerservice.Empty
}
var file_pkg_shortenerservice_shortenerservice_proto_depIdxs = []int32{
	5, // 0: shortenerservice.UserURLsResponse.url:type_name -> shortenerservice.URLData
	0, // 1: shortenerservice.ShortenerService.ShortenURL:input_type -> shortenerservice.URLShortenRequest
	2, // 2: shortenerservice.ShortenerService.ExpandURL:input_type -> shortenerservice.URLExpandRequest
	6, // 3: shortenerservice.ShortenerService.ListUserURLs:input_type -> shortenerservice.Empty
	1, // 4: shortenerservice.ShortenerService.ShortenURL:output_type -> shortenerservice.URLShortenResponse
	3, // 5: shortenerservice.ShortenerService.ExpandURL:output_type -> shortenerservice.URLExpandResponse
	4, // 6: shortenerservice.ShortenerService.ListUserURLs:output_type -> shortenerservice.UserURLsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_shortenerservice_shortenerservice_proto_init() }
func file_pkg_shortenerservice_shortenerservice_proto_init() {
	if File_pkg_shortenerservice_shortenerservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_shortenerservice_shortenerservice_proto_rawDesc), len(file_pkg_shortenerservice_shortenerservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_shortenerservice_shortenerservice_proto_goTypes,
		DependencyIndexes: file_pkg_shortenerservice_shortenerservice_proto_depIdxs,
		MessageInfos:      file_pkg_shortenerservice_shortenerservice_proto_msgTypes,
	}.Build()
	File_pkg_shortenerservice_shortenerservice_proto = out.File
	file_pkg_shortenerservice_shortenerservice_proto_goTypes = nil
	file_pkg_shortenerservice_shortenerservice_proto_depIdxs = nil
}
