package resetgen

import (
	"go/format"
	"os"
	"path/filepath"
	"testing"

	"github.com/konkovaanna23/shortener/internal/file"
	"golang.org/x/tools/go/packages"
)

var content string = `
package main

// generate:reset
type FirstStruct struct {
    Name string
    Age  int
	Three *ThreeStruct
	
}

// generate:reset
type TwoStruct struct {
    Value []float64
	ValueMap map[int]int
}


// generate:reset
type ThreeStruct struct {
    Value int
}

func (t *ThreeStruct) Reset() {
	t.Value=0
}
`

var contentReset string = `// Code generated by generate-reset; DO NOT EDIT.

package main

func (f *FirstStruct) Reset() {
	
	f.Name=""

	f.Age=0

	if t.Three!=nil {
		t.Reset()
	}

}

func (t *TwoStruct) Reset() {
	
	t.Value=t.Value[:0]

	clear(t.ValueMap)

}

  func (t *ThreeStruct) Reset() {

    t.Value = 0

   }

`

func TestProcessPackage(t *testing.T) {
	tmpDir := t.TempDir()

	// 1) обязательно создаём go.mod
	goMod := `module example.com/testpkg

go 1.22
`
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}

	testFile := filepath.Join(tmpDir, "main.go")
	if err := os.WriteFile(testFile, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	cfg := &packages.Config{
		Dir: tmpDir,
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles | // <-- добавь
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo,
		Env: os.Environ(),
	}

	// 2) грузим именно текущий пакет, а не ./...
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		t.Fatalf("load errors")
	}
	if len(pkgs) != 1 {
		t.Fatalf("ожидался 1 пакет, получено %d", len(pkgs))
	}

	pkg := pkgs[0]
	t.Logf("GoFiles: %v", pkg.GoFiles)
	t.Logf("CompiledGoFiles: %v", pkg.CompiledGoFiles)
	t.Logf("Syntax count: %d", len(pkg.Syntax))

	if len(pkg.GoFiles) == 0 {
		t.Fatal("pkg.GoFiles пуст — файлы не подхватились")
	}

	ProcessPackage(pkg)

	genFile := filepath.Join(tmpDir, "reset.gen.go")
	if _, err := os.Stat(genFile); os.IsNotExist(err) {
		t.Fatal("ожидался файл reset.gen.go, но он не был создан")
	}

	data, err := file.ReadFromFile(genFile)
	if err != nil {
		t.Fatal(err)
	}

	generated := string(data)

	formatted, err := format.Source(data)
	if err != nil {
		t.Fatal(err)
	}

	if generated != string(formatted) {
		t.Errorf("сгенерированный код не совпадает с ожидаемым:\n%s", generated)
		t.Errorf("ожидалось:\n%s", string(formatted))
		t.FailNow()
	}

}
